Matrix.Web/Areas/Sales/Controllers/BookController.cs
using Matrix.Core.FrameworkCore;
using Matrix.Core.QueueCore;
using Matrix.Core.SearchCore;
using Matrix.DAL.MongoRepositoriesCustom;
using Matrix.DAL.SearchRepositoriesBase;
using Matrix.Entities.MongoEntities;
using Matrix.Entities.SearchDocuments;
using Matrix.Business.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Matrix.Core.ConfigurationsCore;

namespace Matrix.Web.Areas.Sales.Controllers
{
    public class BookController : Controller
    {
        IBookRepository _bookRepository;

        public BookController(IBookRepository bookRepository)
        {
            this._bookRepository = bookRepository;            
        }

        public ActionResult Index()
        {
            if (MXFlagSettingHelper.Get<bool>("bUseElasticSearchEngine")) ViewBag.IsUsingElasticSearch = true;
            else ViewBag.IsUsingElasticSearch = false;

            //This is being used for checking if sample data is there. No need to do this in real scenarios.
            if (!_bookRepository.IsAnyBookFound)
            {
                ViewBag.ShowDummyButton = true;
            }

            return View();
        }
                
        /// <summary>
        /// the results here are coming from ElasticSearch server
        /// </summary>
        /// <param name="term"></param>
        /// <returns></returns>
        public ActionResult IndexSub(string term = "")
        {
            MXTimer timing = new MXTimer();

            var results = _bookRepository.Search(term);

            ViewBag.QueryTime = timing.Finish();

            return View(results);
        }

        public ActionResult Create()
        {
            MXTimer timing = new MXTimer();

            var model = _bookRepository.GetBookViewModel();
            
            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(BookViewModel model)
        {
            if (ModelState.IsValid)
            {
                _bookRepository.Insert(model);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        #region "Add sample data for books"

        [HttpPost]
        public ActionResult AddSampleData()
        {
            _bookRepository.InsertSampleData();

            return RedirectToAction("Index");
        }

        #endregion
    }//End of controller
}

Matrix.Web/Areas/Sales/Controllers/ClientController.cs
using Matrix.Entities.MongoEntities;
using Matrix.Business.ViewModels;
using Matrix.Core.FrameworkCore;
using Matrix.Core.MongoCore;
using Matrix.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Matrix.DAL.MongoRepositoriesBase;

namespace Matrix.Web.Areas.Sales.Controllers
{
    public class ClientController : Controller
    {
        IMXBusinessMongoRepository _repository;

        public ClientController(IMXBusinessMongoRepository repository)
        {
            this._repository = repository;
        }

        public ActionResult Index()
        {
            MXTimer timing = new MXTimer();

            var model = _repository.GetMany<Client>();

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        public ActionResult CompleteDetails(string id) //id- ClientID
        {
            MXTimer timing = new MXTimer();
                        
            ViewBag.ParentItemName = _repository.GetNameById<Client>(id);

            ViewBag.QueryTime = timing.Finish();

            return View();
        }

        public ActionResult Create()
        {
            return View(new ClientViewModel());
        }

        [HttpPost]
        public ActionResult Create(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {
                _repository.Insert<Client>(model.Client);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(string id)
        {
            MXTimer timing = new MXTimer();

            ClientViewModel model = new ClientViewModel 
            {
                Client = _repository.GetOne<Client>(id),
            };

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {//this one is a bit different because we have embedded Contacts that are not posted back from the same form.                
                _repository.Update(model.Client);

                return RedirectToAction("Edit", new { id = model.Client.Id });
            }
            else
            {
                return View(model.Client.Id);
            }
        }

        #region "async json loads"

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadDataForAutoComplete(string term)
        {
            try
            {
                var predicate = MXPredicateBuilder.True<ClientType>();

                predicate = predicate.And(p => p.Name.ToLower().Contains(term));

                var results = _repository.GetOptionSet<ClientType, DenormalizedReference>(predicate);

                var myData = results.Select(a => new SelectListItem()
                {
                    Text = a.DenormalizedName,
                    Value = a.DenormalizedId,
                });

                return Json(myData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json("Error Occurred: " + ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

    }
}

Matrix.Web/Controllers/EmployeeController.cs
using Matrix.Business.CommonHelpers;
using Matrix.Entities.MongoEntities;
using Matrix.Business.ViewModels;
using Matrix.Core.FrameworkCore;
using Matrix.Core.MongoCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Matrix.DAL.MongoRepositoriesBase;

namespace Matrix.Web.Controllers
{
    public class EmployeeController : Controller
    {
        readonly int takeCount = 40;

        IMXBusinessMongoRepository _repository;

        public EmployeeController(IMXBusinessMongoRepository repository)
        {
            this._repository = repository;
        }

        public ActionResult Index(int? id) //id - pageNo.
        {
            IList<Employee> model;

            MXTimer timing = new MXTimer();

            var page = id ?? 0;

            if (page == 0)
            {
                model = _repository.GetMany<Employee>(take: takeCount);

                model = model.OrderBy(c => c.Name).ToList();

                ViewBag.QueryTime = timing.Finish();

                if (model.Count < 1)
                {
                    ViewBag.ShowDummyButton = true;
                }

                return View(model);
            }

            return PartialView("_Employees", GetPaginatedItems(page));
        }

        private IList<Employee> GetPaginatedItems(int page = 1)
        {
            var skipRecords = page * takeCount;

            MXTimer timing = new MXTimer();

            var model = _repository.GetMany<Employee>(skip: skipRecords, take: takeCount);

            ViewBag.QueryTime = timing.Finish();

            return model;
        }

        public ActionResult Create()
        {
            MXTimer timing = new MXTimer();

            EmployeeViewModel model = new EmployeeViewModel();

            //let's go parallel
            Task[] tasks = new Task[2];

            tasks[0] = Task.Factory.StartNew(
                    () =>
                        model.LstGender = _repository.GetOptionSet<Gender, DenormalizedReference>()
                    );

            tasks[1] = Task.Factory.StartNew(
                    () =>
                        model.LstRating = _repository.GetOptionSet<ProgrammingRating, DenormalizedReference>()
                    );

            model.LstSkill = _repository.GetOptionSet<Skill, DenormalizedReference>().Select(c => new MXCheckBoxItem { DenormalizedReference = c }).ToList();

            Task.WaitAll(tasks);

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(EmployeeViewModel model)
        {
            model.Employee.Gender = _repository.GetOptionById<Gender, DenormalizedReference>(model.Employee.Gender.DenormalizedId);
            model.Employee.ProgrammingRating = _repository.GetOptionById<ProgrammingRating, DenormalizedReference>(model.Employee.ProgrammingRating.DenormalizedId);

            model.Employee.Skills = model.LstSkill.Where(c => c.IsSelected == true).Select(c => c.DenormalizedReference).ToList();

            _repository.Insert<Employee>(model.Employee);
                       
            return RedirectToAction("Index");
        }

        public ActionResult Edit(string id)//employeeId
        {
            MXTimer timing = new MXTimer();

            EmployeeViewModel model = new EmployeeViewModel
            {
                Employee = _repository.GetOne<Employee>(id),
            };

            //let's go parallel
            Task[] tasks = new Task[2];

            tasks[0] = Task.Factory.StartNew(
                    () =>
                        model.LstGender = _repository.GetOptionSet<Gender, DenormalizedReference>()
                    );

            tasks[1] = Task.Factory.StartNew(
                    () =>
                        model.LstRating = _repository.GetOptionSet<ProgrammingRating, DenormalizedReference>()
                    );

            model.LstSkill = _repository.GetOptionSet<Skill, DenormalizedReference>().Select(c => new MXCheckBoxItem { DenormalizedReference = c }).ToList();

            foreach (var item in model.LstSkill)
            {
                if (model.Employee.Skills != null && model.Employee.Skills.Select(c => c.DenormalizedId).Contains(item.DenormalizedReference.DenormalizedId)) 
                    item.IsSelected = true;
            }

            Task.WaitAll(tasks);

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EmployeeViewModel model)
        {
            model.Employee.Gender = _repository.GetOptionById<Gender, DenormalizedReference>(model.Employee.Gender.DenormalizedId);
            model.Employee.ProgrammingRating = _repository.GetOptionById<ProgrammingRating, DenormalizedReference>(model.Employee.ProgrammingRating.DenormalizedId);

            model.Employee.Skills = model.LstSkill.Where(c => c.IsSelected == true).Select(c => c.DenormalizedReference).ToList();

            _repository.Update<Employee>(model.Employee);

            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(string id) //id - employeeID
        {
            _repository.Delete<Employee>(id);

            return RedirectToAction("Index");
        }

        public ActionResult History(string id) //id - employeeID
        {
            MXTimer timing = new MXTimer();

            var model = _repository.GetHistory<Employee>(id);

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult AddDummyEmployees()
        {
            var genders = _repository.GetOptionSet<Gender, DenormalizedReference>();

            var rating = _repository.GetOptionSet<ProgrammingRating, DenormalizedReference>().FirstOrDefault();

            List<Employee> lstEmployee = new List<Employee>();

            for (int count = 0; count < 100; count++)
            {
                var employee = new Employee
                {
                    Name = string.Format("Max Payne{0}", count.ToString()),
                    Gender = count % 2 == 0 ? genders[0] : genders[1],
                    ProgrammingRating = rating,
                    Email = string.Format("MaxPaynee{0}@matrixInc.com", count.ToString()),
                };

                lstEmployee.Add(employee);
            }

            _repository.BulkInsert<Employee>(lstEmployee);

            return RedirectToAction("Index");
        }
        
    }
}

Matrix.Web/Controllers/FlagSettingController.cs
using Matrix.Core.ConfigurationsCore;
using Matrix.Core.FrameworkCore;
using Matrix.DAL.MongoRepositoriesCustom;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Matrix.Web.Controllers
{
    public class FlagSettingController : Controller
    {
        IFlagSettingRepository _repository;

        public FlagSettingController(IFlagSettingRepository repository)
        {
            _repository = repository;
        }

        //
        // GET: /FlagSetting/

        public ActionResult Index()
        {
            MXTimer timing = new MXTimer();

            var model = _repository.Get();

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        //
        // GET: /FlagSetting/Create

        public ActionResult Create()
        {
            var model = new FlagSetting();

            return View(model);
        }

        //
        // GET: /FlagSetting/Edit/5

        public ActionResult Edit(string id)
        {
            MXTimer timing = new MXTimer();

            var model = _repository.GetOne(id);

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        //
        // POST: /FlagSetting/Edit/5

        [HttpPost]
        public ActionResult Save(FlagSetting model)
        {
            _repository.Save(model);

            return RedirectToAction("Index");
        }

        //
        // GET: /FlagSetting/Delete/5

        public ActionResult Delete(string id)
        {
            _repository.Delete(id);

            return RedirectToAction("Index");
        }

    }//End of controller
}

Matrix.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" />
    <link href="~/Content/themes/base/MXWeb.css" rel="stylesheet" />
</head>
<body>
    <table>
        <tr>
            <td class="leftMenu">
                <!--Put menu items here -->
            
                @Ajax.ActionLink("My Employees", "Index", "Employee",
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })
                <br />
                 @Ajax.ActionLink("My Clients", "Index", "Client", new { area = "Sales" },
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            }, null)
                <br />
            @Ajax.ActionLink("Product Catalog", "Index", "Book", new { area = "Sales" },
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            }, null)
                <br />
            @Ajax.ActionLink("About Me", "About", "Home",
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })
                <br />
                <br />
                <br />

            @Ajax.ActionLink("Flag Settings", "Index", "FlagSetting",
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })
                <div id="divLoading" style="display: none;">
                        @*@Html.JQueryUI().Progressbar(null)*@
                        <img src="~/Content/themes/base/images/wait.gif" />
                </div>    

            </td>
            <td style="vertical-align:top;">
                <div id="divContent" style="margin-left:2%;">
                    @RenderBody()
                </div>
            </td>
        </tr>
    </table>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/MatrixWebScript.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>


<script type="text/javascript">
   
</script>

Matrix.Web/Views/Shared/_MXClientValidation.cshtml
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript" />

<div style="vertical-align:top;">
    @RenderBody()
</div>

Matrix.Web/Views/Shared/_QueryTime.cshtml
@*@model string*@
@{
    Layout = null;
}
@if (Matrix.Core.ConfigurationsCore.MXFlagSettingHelper.Get<bool>("bShowLoadTime"))
{
    <div style="border:1px solid green; margin-left:85%;font-size:smaller;">
        Query Time : <b>@ViewBag.QueryTime</b>
    </div>
}