Matrix.Web/Areas/Sales/Controllers/ClientContactController.cs
using Matrix.Entities.MongoEntities;
using Matrix.Business.ViewModels;
using Matrix.Core.FrameworkCore;
using Matrix.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Matrix.DAL.MongoRepositoriesBase;
using Matrix.Core.MongoCore;

namespace Matrix.Web.Areas.Sales.Controllers
{
    public partial class ClientContactController : Controller
    {

        IMXBusinessMongoRepository _repository;

        public ClientContactController(IMXBusinessMongoRepository repository)
        {
            this._repository = repository;
        }

        public ActionResult Index(string id) //id - clientID
        {
            MXTimer timing = new MXTimer();

            var model = _repository.GetOne<Client>(id);

            ViewBag.QueryTime = timing.Finish();

            return View(model); 
        }

        public ActionResult Create(string id) //id - clientID
        {
            return View(new ClientViewModel { Client = new Client { Id = id } });
        }

        [HttpPost]
        public ActionResult Create(ClientViewModel model)
        {
            Client client = _repository.GetOne<Client>(model.Client.Id);

            if (client.Contacts == null)
            {
                client.Contacts = new List<Contact>();
            }

            model.Client.Contacts[0].Id = MXMongoIdGenerator.NewId;

            client.Contacts.Add(model.Client.Contacts[0]);

            _repository.Update<Client>(client);

            return RedirectToAction("Index", new { id = model.Client.Id });
        }

    }//end of controller
}

Matrix.Web/Areas/Sales/Controllers/ClientController.cs
using Matrix.Entities.MongoEntities;
using Matrix.Business.ViewModels;
using Matrix.Core.FrameworkCore;
using Matrix.Core.MongoCore;
using Matrix.Web.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Matrix.DAL.MongoRepositoriesBase;

namespace Matrix.Web.Areas.Sales.Controllers
{
    public class ClientController : Controller
    {
        IMXBusinessMongoRepository _repository;

        public ClientController(IMXBusinessMongoRepository repository)
        {
            this._repository = repository;
        }

        public ActionResult Index()
        {
            MXTimer timing = new MXTimer();

            var model = _repository.GetMany<Client>();

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        public ActionResult CompleteDetails(string id) //id- ClientID
        {
            MXTimer timing = new MXTimer();
                        
            ViewBag.ParentItemName = _repository.GetNameById<Client>(id);

            ViewBag.QueryTime = timing.Finish();

            return View();
        }

        public ActionResult Create()
        {
            return View(new ClientViewModel());
        }

        [HttpPost]
        public ActionResult Create(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {
                _repository.Insert<Client>(model.Client);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        public ActionResult Edit(string id)
        {
            MXTimer timing = new MXTimer();

            ClientViewModel model = new ClientViewModel 
            {
                Client = _repository.GetOne<Client>(id),
            };

            ViewBag.QueryTime = timing.Finish();

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ClientViewModel model)
        {
            if (ModelState.IsValid)
            {//this one is a bit different because we have embedded Contacts that are not posted back from the same form.                
                _repository.Update(model.Client);

                return RedirectToAction("Edit", new { id = model.Client.Id });
            }
            else
            {
                return View(model.Client.Id);
            }
        }

        #region "async json loads"

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadDataForAutoComplete(string term)
        {
            try
            {
                var predicate = MXPredicateBuilder.True<ClientType>();

                predicate = predicate.And(p => p.Name.ToLower().Contains(term));

                var results = _repository.GetOptionSet<ClientType, DenormalizedReference>(predicate);

                var myData = results.Select(a => new SelectListItem()
                {
                    Text = a.DenormalizedName,
                    Value = a.DenormalizedId,
                });

                return Json(myData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json("Error Occurred: " + ex.Message, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

    }
}

Matrix.Web/Areas/Sales/Views/Client/CompleteDetails.cshtml
@{
    //ViewBag.Title = "CompleteDetails";
    Layout = null;//"~/Views/Shared/_Layout.cshtml";
}
@Ajax.ActionLink("<< Back", "Index", "Client",
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })
<h2>Complete Details of "@ViewBag.ParentItemName"</h2>

<div id="divClientCompleteDetails" style="height: auto; width: auto">
    <ul>
        <li><a href="#divClientInfo"><span>Info</span></a></li>
        <li><a href="#divClientContacts" id="hlClientContacts"><span>Contacts</span></a></li>        
    </ul>

    <div id="divClientInfo">
    </div>

    <div id="divClientContacts">

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#divClientCompleteDetails").tabs();

        getContent('divClientInfo', '@Html.Raw(Url.Action("Edit", "Client", new { id = ViewContext.RouteData.Values["id"] }))', 'False');
                

        $("#hlClientContacts").click(function () {
            getContent('divClientContacts', '@Html.Raw(Url.Action("Index", "ClientContact", new { id = ViewContext.RouteData.Values["id"] }))', 'False');
        });
    });
</script>

Matrix.Web/Areas/Sales/Views/Client/Create.cshtml
@model Matrix.Business.ViewModels.ClientViewModel
@{
    Layout = "~/Views/Shared/_MXClientValidation.cshtml";
}
@Html.Partial("_QueryTime")
<h2>Create a new Client</h2>
<div>
<b>Note</b>: Saving a client is critical to us. We cannot afford to loose out on potential business; hence this is queued to RabbitMQ.
</div>

@using (Ajax.BeginForm("Create", "Client",
    new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace
            }))
{   
    <table>
        <tr>
            <td>Name:</td>
            <td>@Html.EditorFor(x => x.Client.Name)
            </td>

            <td>Type:</td>
            <td>
                @Html.TextBoxFor(x => x.Client.ClientType.DenormalizedName, new { id = "txtClientTypeAutoComplete" })
                @Html.HiddenFor(x => x.Client.ClientType.DenormalizedId, new { id = "hdnSelectedClientTypeId" })
                <br />
                @Html.ValidationMessageFor(x => x.Client.ClientType)
                <span style="font-size: small">(Start typing for autocomplete such as 'info' or 'energy', this data is generated while setting up master data in the root page)
                </span>
            </td>
        </tr>

        <tr>
            <td>Code:</td>
            <td>@Html.EditorFor(x => x.Client.Code)
            </td>

            <td>Phone:</td>
            <td>@Html.EditorFor(x => x.Client.PhoneNumber)
            </td>
        </tr>

        <tr>
            <td>Website:</td>
            <td>@Html.EditorFor(x => x.Client.Website)
            </td>

            <td>Address:</td>
            <td>@Html.TextAreaFor(x => x.Client.Address)
            </td>
        </tr>
    </table>
    <div>
        <br />
        <br />
        <input id="btnSubmit" name="btnSubmit" value="Create" type="submit" />
        @Ajax.ActionLink("<< Back", "Index", "Client", null,
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })


    </div>
}

<script type="text/javascript">

    $("#txtClientTypeAutoComplete").blur(function () {
        $(this).valid();
    });

    $("#txtClientTypeAutoComplete").live('input', function () {
        var content = $("#txtClientTypeAutoComplete").val();
        if (content == "") {
            $("#hdnSelectedClientTypeId").val(null);
        }
    })

    $(function () {
        $("#txtClientTypeAutoComplete").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/Client/LoadDataForAutoComplete', type: "GET", dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.Text, value: item.Value, id: item.Value };
                        }))
                    }
                })
            },

            focus: function (event, ui) {
                $("#txtClientTypeAutoComplete").val(ui.item.label);
                return false;
            },

            minLength: 3,
            autofill: true,
            select: function (event, ui) {
                $("#txtClientTypeAutoComplete").val(ui.item.label);
                $("#hdnSelectedClientTypeId").val(ui.item.value);
                event.preventDefault();
            }
        });
    });

</script>

Matrix.Web/Areas/Sales/Views/Client/Edit.cshtml
@model Matrix.Business.ViewModels.ClientViewModel
@{
    Layout = "~/Views/Shared/_MXClientValidation.cshtml";
}
@Html.Partial("_QueryTime")

@using (Ajax.BeginForm("Edit", "Client",
    new AjaxOptions
            {
                UpdateTargetId = "divClientInfo",
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace
            }))
{   
    @Html.HiddenFor(x => x.Client.Id)   
    @Html.HiddenFor(x => x.Client.Version)   
    
    <table>
        <tr>
            <td>Name:</td>
            <td>@Html.EditorFor(x => x.Client.Name)
            </td>
                    
            <td>Type:</td>
            <td>
                @Html.TextBoxFor(x => x.Client.ClientType.DenormalizedName, new { id = "txtClientTypeAutoComplete" })
                @Html.HiddenFor(x => x.Client.ClientType.DenormalizedId, new { id = "hdnSelectedClientTypeId" })
                <br />
                @Html.ValidationMessageFor(x => x.Client.ClientType)
                <span style="font-size:small">
                    (Start typing for autocomplete such as 'info' or 'energy', this data is generated while setting up master data in the root page)</span>
            </td>            
        </tr>

        <tr>
            <td>Code:</td>
            <td>@Html.EditorFor(x => x.Client.Code)
            </td>
                    
            <td>Phone:</td>
            <td>@Html.EditorFor(x => x.Client.PhoneNumber)
            </td>
        </tr>

        <tr>
            <td>Website:</td>
            <td>@Html.EditorFor(x => x.Client.Website)
            </td>
                    
            <td>Address:</td>
            <td>@Html.TextAreaFor(x => x.Client.Address)
            </td>
        </tr>
    </table>
    <div>
        <br />        
        <input id="btnSubmit" name="btnSubmit" value="Save" type="submit" />

    </div>
}

<script type="text/javascript">

    $("#txtClientTypeAutoComplete").blur(function () {
        $(this).valid();
    });

    $("#txtClientTypeAutoComplete").live('input', function () {
        var content = $("#txtClientTypeAutoComplete").val();
        if (content == "") {
            $("#hdnSelectedClientTypeId").val(null);
        }
    })

    $(function () {
        $("#txtClientTypeAutoComplete").autocomplete({
            source: function (request, response) {
                $.ajax({
                    url: '/Client/LoadDataForAutoComplete', type: "GET", dataType: "json",
                    data: { term: request.term },
                    success: function (data) {
                        response($.map(data, function (item) {
                            return { label: item.Text, value: item.Value, id: item.Value };
                        }))
                    }
                })
            },

            focus: function (event, ui) {
                $("#txtClientTypeAutoComplete").val(ui.item.label);
                return false;
            },

            minLength: 3,
            autofill: true,
            select: function (event, ui) {
                $("#txtClientTypeAutoComplete").val(ui.item.label);
                $("#hdnSelectedClientTypeId").val(ui.item.value);
                event.preventDefault();
            }
        });
    });

</script>

Matrix.Web/Areas/Sales/Views/Client/Index.cshtml
@model IList<Matrix.Entities.MongoEntities.Client>

@{
    //ViewBag.Title = "_Elements";
    Layout = null; //"~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_QueryTime")

<h2>My Clients</h2>
<div>
<b>Note</b>: Saving a new client is critical to us. We cannot afford to loose out on potential business; hence creating a new client is queued to RabbitMQ. 
    <br />
    Do not forget to run the subscriber application at "..\Matrix.Processor\bin\Debug\Matrix.Processor.exe". You can run multiple instances of the subscriber as well.
    If you do not see the just added client, please refresh the listing here  
    @Ajax.ActionLink("Refresh", "Index", "Client", null,
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading",
            })
</div>
<br />
@Ajax.ActionLink("Add A New Client", "Create", null,
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading"
            }, new { @class="nav" })<br /><br />


@if (Model != null && Model.Count > 0)
{
    <table border="1">
        <tr>
            <th>Name</th>
            <th>Code</th>     
            <th>Type</th>         
            <th>Phone</th>            
            <th>Website</th>
            <th>Revision</th>
        </tr>

        @foreach (var item in Model)
    {                  
        <tr>           
            <td>
                @Ajax.ActionLink(item.Name, "CompleteDetails", "Client", 
            new { 
                    id = item.Id,
            },
            new AjaxOptions
            {
                UpdateTargetId = "divContent",
                HttpMethod = "Get",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "divLoading"
            })</td>
            <td>@item.Code</td>
            <td>@item.ClientType.DenormalizedName</td>
            <td>@item.PhoneNumber</td>
            <td>@item.Website</td>
            <td>@item.Version</td>
        </tr>
        }
    
    </table>
}
else
{    
    <br />
    @Html.Label("NO DATA FOUND")
}